apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    type: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fe-app
  template:
    metadata:
      name: fe-app
      labels:
        type: frontend-app
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            containerPort: 80


