apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    type: frontend-app
spec:
  replicas: 1
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-deployment
        type: frontend-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      name: redis-deployment
      type: frontend-app
